// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		//getting the user input
		int nTimes = Integer.parseInt(args[0]);

		//defining 2 counters
        int counterBigger = 0;
        int counterSmaller = 0;

        for (int i = 0; i < nTimes; i++) {
            double randomNumber = Math.random();
			//adding to the counter besed on the if
            if (randomNumber > 0.5) {
                counterBigger++;
            } else {
                counterSmaller++;
            }
        }

        System.out.println("> 0.5: " + counterBigger + " times");
        System.out.println("<= 0.5: " + counterSmaller + " times");

		//just making sure in not deviding by 0 
        if (counterSmaller != 0) {
            double ratio = (double) counterBigger / counterSmaller;
            System.out.println("Ratio: " + ratio);
        } else {
            System.out.println("deviding by 0");
        }
	}
		
}
